/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ITTech
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleLbl = new javax.swing.JLabel();
        Q1Lbl = new javax.swing.JLabel();
        Q2Lbl = new javax.swing.JLabel();
        Q3Lbl = new javax.swing.JLabel();
        Q4Lbl = new javax.swing.JLabel();
        Q5Lbl = new javax.swing.JLabel();
        Q1Txt = new javax.swing.JTextField();
        Q1Btn = new javax.swing.JButton();
        A1Lbl = new javax.swing.JLabel();
        Q2Txt = new javax.swing.JTextField();
        Q2Btn = new javax.swing.JButton();
        A2Lbl = new javax.swing.JLabel();
        Q3Txt = new javax.swing.JTextField();
        Q3Btn = new javax.swing.JButton();
        A3Lbl = new javax.swing.JLabel();
        Q4Txt1 = new javax.swing.JTextField();
        Q4Txt2 = new javax.swing.JTextField();
        Q4Btn = new javax.swing.JButton();
        A4Lbl = new javax.swing.JLabel();
        Q5Txt1 = new javax.swing.JTextField();
        Q5Txt2 = new javax.swing.JTextField();
        Q5Btn = new javax.swing.JButton();
        A5Lbl = new javax.swing.JLabel();
        Q6Lbl = new javax.swing.JLabel();
        Q7Lbl = new javax.swing.JLabel();
        Q6Txt = new javax.swing.JTextField();
        A6Lbl = new javax.swing.JLabel();
        Q6Btn = new javax.swing.JButton();
        Q7Txt = new javax.swing.JTextField();
        A7Lbl = new javax.swing.JLabel();
        Q7Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLbl.setText("Super String Software");

        Q1Lbl.setText("Enter a String. This program outputs the number of characters in the string.");

        Q2Lbl.setText("Enter a String in lowercase letters. This program wil output the string in UPPERCASE letters.");

        Q3Lbl.setText("Enter a string. The program will output the character in the 4th character spot.");

        Q4Lbl.setText("Enter two Strings. The program will determine if they are identical or not.");

        Q5Lbl.setText("Enter a String and a letter. The program will output if the letter is found in the String");

        Q1Btn.setText("Length");
        Q1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1BtnActionPerformed(evt);
            }
        });

        A1Lbl.setText("-");

        Q2Btn.setText("All Caps");
        Q2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2BtnActionPerformed(evt);
            }
        });

        A2Lbl.setText("-");

        Q3Btn.setText("4th Spot");
        Q3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3BtnActionPerformed(evt);
            }
        });

        A3Lbl.setText("-");

        Q4Btn.setText("Identical?");
        Q4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4BtnActionPerformed(evt);
            }
        });

        A4Lbl.setText("-");

        Q5Btn.setText("Letter Found?");
        Q5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q5BtnActionPerformed(evt);
            }
        });

        A5Lbl.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Q1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Q1Btn)
                        .addGap(74, 74, 74)
                        .addComponent(A1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Q5Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Q4Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(TitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Q1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Q2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Q3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Q2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Q2Btn)
                        .addGap(74, 74, 74)
                        .addComponent(A2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Q3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Q3Btn)
                        .addGap(74, 74, 74)
                        .addComponent(A3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Q4Txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Q4Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Q4Btn)
                                .addGap(37, 37, 37)
                                .addComponent(A4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Q5Txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Q5Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Q5Btn)
                                .addGap(37, 37, 37)
                                .addComponent(A5Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLbl)
                .addGap(18, 18, 18)
                .addComponent(Q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q1Btn)
                    .addComponent(A1Lbl))
                .addGap(20, 20, 20)
                .addComponent(Q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q2Btn)
                    .addComponent(A2Lbl))
                .addGap(33, 33, 33)
                .addComponent(Q3Lbl)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q3Btn)
                    .addComponent(A3Lbl))
                .addGap(18, 18, 18)
                .addComponent(Q4Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q4Txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q4Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q4Btn)
                    .addComponent(A4Lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(Q5Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q5Txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q5Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q5Btn)
                    .addComponent(A5Lbl)))
        );

        Q6Lbl.setText("Enter a String that is at least 8 letters. This program will output characters 4-6");

        Q7Lbl.setText("Enter a String that contains at least 1 \"a\". The program will replace all \"a\"s with \"x\"");

        A6Lbl.setText("-");

        Q6Btn.setText("Characters 4-6");
        Q6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q6BtnActionPerformed(evt);
            }
        });

        A7Lbl.setText("-");

        Q7Btn.setText("Replace that A ");
        Q7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q7BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q6Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Q7Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Q6Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Q6Btn)
                        .addGap(74, 74, 74)
                        .addComponent(A6Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Q7Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Q7Btn)
                        .addGap(74, 74, 74)
                        .addComponent(A7Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q6Lbl)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q6Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q6Btn)
                    .addComponent(A6Lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q7Lbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q7Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q7Btn)
                    .addComponent(A7Lbl))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Q1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1BtnActionPerformed
        String userInput; //Variable Declaration Area
        userInput = Q1Txt.getText(); //Getting input from user
        A1Lbl.setText(String.valueOf(userInput.length())); // Using the String Method to complete the user's request, and outputing the info to the user
        // Above I converted a integer to a string.
    }//GEN-LAST:event_Q1BtnActionPerformed

    private void Q2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2BtnActionPerformed
        String userInput; //Variable Declaration Area
        userInput = Q2Txt.getText(); //Getting input from user
        A2Lbl.setText(userInput.toUpperCase());  // Using the String Method to complete the user's request, and outputing the info to the user
    }//GEN-LAST:event_Q2BtnActionPerformed

    private void Q3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3BtnActionPerformed
        String userInput; //Variable Declaration Area
        userInput = Q3Txt.getText(); //Getting input from user
        A3Lbl.setText(String.valueOf(userInput.charAt(3)));  // Using the String Method to complete the user's request, and outputing the info to the user
        // Converted a char to a string
    }//GEN-LAST:event_Q3BtnActionPerformed

    private void Q4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4BtnActionPerformed
        String userInput; //Variable Declaration Area
        String userInputTwo;
        userInput = Q4Txt1.getText(); //Getting input from user
        userInputTwo = Q4Txt2.getText();
        // If/Else to determine if they are identical or not, then outputing the answer to the user
        if (userInput.equals(userInputTwo))
        {
        A4Lbl.setText("Identical");
        }
        else 
        {
        A4Lbl.setText("Not Identical");
        }
    }//GEN-LAST:event_Q4BtnActionPerformed

    private void Q5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q5BtnActionPerformed
        String userInput; //Variable Declaration Area
        String userInputTwo;
        userInput = Q5Txt1.getText(); //Getting input from user
        userInputTwo = Q5Txt2.getText();
        //If Else statement to check if the character is in the String, then outputing the answer to the user
        if (userInput.contains(userInputTwo))
        {
        A5Lbl.setText("Found in String");
        }
        else 
        {
        A5Lbl.setText("Not Found in string");
        }
    }//GEN-LAST:event_Q5BtnActionPerformed

    private void Q6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q6BtnActionPerformed
        String userInput; //Variable Declaration Area
        userInput = Q6Txt.getText(); //Getting input from user
        // Below I determine the character at positions 4-6, then output them in order to the user
        A6Lbl.setText(String.valueOf(userInput.charAt(3)) + String.valueOf(userInput.charAt(4)) + String.valueOf(userInput.charAt(5)));
    }//GEN-LAST:event_Q6BtnActionPerformed

    private void Q7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q7BtnActionPerformed
        String userInput; //Variable Declaration Area
        userInput = Q7Txt.getText(); //Getting input from user
        // Using the replace method to replace all letter A to X
        String userOutput = userInput.replace("a","x");
        A7Lbl.setText(userOutput);
    }//GEN-LAST:event_Q7BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1Lbl;
    private javax.swing.JLabel A2Lbl;
    private javax.swing.JLabel A3Lbl;
    private javax.swing.JLabel A4Lbl;
    private javax.swing.JLabel A5Lbl;
    private javax.swing.JLabel A6Lbl;
    private javax.swing.JLabel A7Lbl;
    private javax.swing.JButton Q1Btn;
    private javax.swing.JLabel Q1Lbl;
    private javax.swing.JTextField Q1Txt;
    private javax.swing.JButton Q2Btn;
    private javax.swing.JLabel Q2Lbl;
    private javax.swing.JTextField Q2Txt;
    private javax.swing.JButton Q3Btn;
    private javax.swing.JLabel Q3Lbl;
    private javax.swing.JTextField Q3Txt;
    private javax.swing.JButton Q4Btn;
    private javax.swing.JLabel Q4Lbl;
    private javax.swing.JTextField Q4Txt1;
    private javax.swing.JTextField Q4Txt2;
    private javax.swing.JButton Q5Btn;
    private javax.swing.JLabel Q5Lbl;
    private javax.swing.JTextField Q5Txt1;
    private javax.swing.JTextField Q5Txt2;
    private javax.swing.JButton Q6Btn;
    private javax.swing.JLabel Q6Lbl;
    private javax.swing.JTextField Q6Txt;
    private javax.swing.JButton Q7Btn;
    private javax.swing.JLabel Q7Lbl;
    private javax.swing.JTextField Q7Txt;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
